export const ROUTE_PATHS = {
  dashboard: '/',
  login: '/login',
  patients: '/patients',
  patientCreate: '/patients/create',
  patientDetail: '/patients/:id',
  patientEdit: '/patients/:id/edit',
  glucoseOverview: '/glucose',
  dietManage: '/diet',
  notifications: '/notifications',
  followupTemplates: '/followup/templates',
  followupTemplateCreate: '/followup/templates/create',
  followupTemplateEdit: '/followup/templates/:id',
  systemUsers: '/system/users',
  systemConfig: '/system/config',
} as const
