from app.schemas.auth import LoginRequest, RegisterRequest, TokenResponse, UserRead
from app.schemas.common import ApiResponse, PageData
from app.schemas.dashboard import (
    DashboardDistributionItem,
    DashboardGlucoseTrend,
    DashboardPatientOverview,
    DashboardPendingItem,
    DashboardStats,
    DashboardTrendPoint,
)
from app.schemas.diet import (
    DietMealPlan,
    DietRecommendationContent,
    DietRecommendationGenerateRequest,
    DietRecommendationRead,
    DietRecommendationReviewRequest,
)
from app.schemas.followup import (
    FollowupPlanCreate,
    FollowupPlanRead,
    FollowupPlanUpdate,
    FollowupStageCreate,
    FollowupStageRead,
    FollowupTemplateCreate,
    FollowupTemplateRead,
    FollowupTemplateUpdate,
    StageTaskCreate,
    StageTaskRead,
)
from app.schemas.glucose import (
    BloodGlucoseRecordCreate,
    BloodGlucoseRecordRead,
    GlucoseOverview,
    GlucoseStats,
    GlucoseTrend,
    GlucoseTrendPoint,
)
from app.schemas.h5 import H5AccessLinkRead, H5GlucoseCreate, H5PatientInfo, H5TaskItem
from app.schemas.notification import NotificationRead, NotificationUnreadCount
from app.schemas.patient import (
    PatientCreate,
    PatientDetail,
    PatientListItem,
    PatientTagAssignRequest,
    PatientTagCreate,
    PatientTagRead,
    PatientTagUpdate,
    PatientUpdate,
)
from app.schemas.system import (
    SystemConfigRead,
    SystemConfigUpdateItem,
    SystemUserCreate,
    SystemUserRead,
    SystemUserUpdate,
)

__all__ = [
    "ApiResponse",
    "BloodGlucoseRecordCreate",
    "BloodGlucoseRecordRead",
    "DashboardDistributionItem",
    "DashboardGlucoseTrend",
    "DashboardPatientOverview",
    "DashboardPendingItem",
    "DashboardStats",
    "DashboardTrendPoint",
    "DietMealPlan",
    "DietRecommendationContent",
    "DietRecommendationGenerateRequest",
    "DietRecommendationRead",
    "DietRecommendationReviewRequest",
    "FollowupPlanCreate",
    "FollowupPlanRead",
    "FollowupPlanUpdate",
    "FollowupStageCreate",
    "FollowupStageRead",
    "FollowupTemplateCreate",
    "FollowupTemplateRead",
    "FollowupTemplateUpdate",
    "GlucoseOverview",
    "GlucoseStats",
    "GlucoseTrend",
    "GlucoseTrendPoint",
    "H5AccessLinkRead",
    "H5GlucoseCreate",
    "H5PatientInfo",
    "H5TaskItem",
    "LoginRequest",
    "NotificationRead",
    "NotificationUnreadCount",
    "PageData",
    "PatientCreate",
    "PatientDetail",
    "PatientListItem",
    "PatientTagAssignRequest",
    "PatientTagCreate",
    "PatientTagRead",
    "PatientTagUpdate",
    "PatientUpdate",
    "RegisterRequest",
    "StageTaskCreate",
    "StageTaskRead",
    "SystemConfigRead",
    "SystemConfigUpdateItem",
    "SystemUserCreate",
    "SystemUserRead",
    "SystemUserUpdate",
    "TokenResponse",
    "UserRead",
]
